### ISSUE TITLE
Consider leaving empty storage space in contracts for future enhancements

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-zos#13]
Adding new storage variables to a contract that has been extended by another is impossible, since the storage from the child contract will clash with the new variables added by the parent. To mitigate this, we can "reserve" a few slots in the base contracts, to allow for new variables to be added later. This could be done by declaring some fixed-length `uint256` arrays in storage, until https://github.com/ethereum/solidity/issues/4519 is implemented.

**Comment by frangio** [comment]
To do this we'll add an integer array state variable of length 50 at the end of each contract before the closing brace as follows.

```solidity
contract Foo {
  ...
  uint256[50] ______gap;
}
```
