### ISSUE TITLE
Deploy latest minor versions to Rinkeby

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-zos#19]
Latest minor updates (1.9.2, 1.9.3 and 1.9.4) were not deployed to Rinkeby. Please consider providing support for that testnet as well.

**Comment by frangio** [comment]
Since we can't change the versions that have already been published on npm, I don't think we can do anything about 1.9.2, 1.9.3, and 1.9.4.

Rinkeby is already in the list of networks for 2.0 in #15, and will remain in that list for releases going forward.
