### ISSUE TITLE
Upgrade zos-lib dependency and use its Initializable

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-zos#7]
On version 1.9.2, we are listing `zos-lib@^0.1.26` as a required peer dependency, which should be upgradeable to the `1.4.1` being used by the CLI now. 

Check if the the dependency is actually needed, and can be removed or upgraded.

**Comment by frangio** [comment]
As discussed in https://github.com/zeppelinos/zos/issues/143, we're keeping the peer dependency. It should be upgraded though.

**Comment by frangio** [comment]
PR #18 introduced our own copy of `Initializable` but we should use the one provided in `zos-lib` after `zos-lib` includes the changes we need and once perform this upgrade.

**Comment by spalladino** [comment]
Those changes are in https://github.com/zeppelinos/zos/pull/167
